version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "development"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    schedule:
      interval: "monthly"
