name: Build

on:
  push:
    branches-ignore:
      - gh-pages # no need
      - master # gets done in other workflow

jobs:
  analyze:
    name: Code QL
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Run scripts
        shell: bash
        run: |
          for f in ./etc/scripts/*.sh; do
            echo running $f
            bash $f
          done

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # Build steps
      - name: Install
        run: npm install

      - name: Test
        run: npm run test

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
