name: Build and analyze
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    types: [ opened, synchronize, reopened ]
  schedule:
    - cron: '0 1 * * 6'

jobs:
  analyze:
    name: Build and analyze 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run scripts
        shell: bash
        run: |
          for f in ./etc/scripts/*.sh; do
            echo running $f
            bash $f
          done
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
      - name: NPM install
        run: npm install
      - name: NPM build
        run: npm run build
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1