name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test