name: Build and quality check
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Code standards
    runs-on: ubuntu-latest
    steps:
      - name: "checkout repository"
        uses: actions/checkout@v4

      - name: "setup node"
        uses: actions/setup-node@v4
        with:
          cache: "npm"

      - name: "install dependencies"
        run: npm ci

      - name: "lint code"
        run: npm run lint
