name: End2End

on:
  pull_request:
  schedule:
    - cron: '43 9 * * 3'

jobs:
  e2e-test:
    name: E2e tests
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3

      - name: "🔧 setup node"
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: "🧪 run cypress tests"
        uses: cypress-io/github-action@v5.0.2
        with:
          build: npm run build
          start: npm run local