name: End2End

on:
  pull_request:
  schedule:
    - cron: '43 9 * * 3'

jobs:
  install:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107
      options: --user 1001
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false

      - run: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build

  e2e-chrome-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: E2E - Chrome
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          browser: chrome
          start: npm run local
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: true
          group: "E2E - Chrome"

  e2e-chrome-mobile-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: E2E - Chrome - mobile
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          browser: chrome
          config: "viewportWidth=375,viewportHeight=667"
          start: npm run local
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: true
          group: "E2E - Chrome - mobile"

  e2e-firefox-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: E2E - Firefox
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          browser: firefox
          start: npm run local
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: true
          group: "E2E - Firefox"

  e2e-firefox-mobile-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    container:
      image: cypress/browsers:node16.16.0-chrome107-ff107
      options: --user 1001
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: E2E - Firefox - mobile
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          browser: firefox
          config: "viewportWidth=375,viewportHeight=667"
          start: npm run local
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: true
          group: "E2E - Firefox - mobile"

  e2e-electron-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build folders
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: E2E - Electron
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          start: npm run local
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          record: true
          group: "E2E - Electron"