name: Build & deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Run scripts
        shell: bash
        run: |
          for f in ./etc/scripts/*.sh; do
            echo running $f
            bash $f
          done

      - name: NPM deploy
        run: |
          npm run deploy