name: Build & deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ published ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: User Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: NPM tests
        run: |
          npm install
          npm test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Run scripts
        shell: bash
        run: |
          for f in ./etc/scripts/*.sh; do
            echo running $f
            bash $f
          done

      - name: Setup git credentials
        env:
          USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config user.email "$USER_EMAIL"
          git config user.name "Action deployer"

      - name: NPM deploy
        run: |
          npm install
          npm run deploy