name: Outgoing links check
on:
  pull_request:
  schedule:
    - cron: "43 9 1 * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - uses: actions/upload-artifact@v3
        name: Upload build folder
        with:
          name: npm-build
          path: ./dist/
          retention-days: 1
  e2e-third-party:
    needs: build
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: npm-build
          path: ./dist/
      - name: E2E - Third party
        uses: cypress-io/github-action@v6
        with:
          project: "./test/driver/cypress"
          browser: electron
          start: npm run preview:local
          wait-on: "http://localhost:9000"
          wait-on-timeout: 15
          spec: "**/e2e/third-party/**/*"
