name: Patch version
on:
  push:
    branches:
      - dev

jobs:
  patch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.RELEASE_TOKEN }}

      - name: "🔧 setup node"
        uses: actions/setup-node@v3
        with:
          cache: 'npm'

      - name: "📦 patch"
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          npm run patch
          git push