name: GCP Deploy
on:
  release:
    types: [ published ]
jobs:
  Deploy:
    name: Deployment to GCP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Run scripts
        shell: bash
        run: |
          for f in ./etc/scripts/*.sh; do
            echo running $f
            bash $f
          done


      - name: NPM build
        run: |
          npm install
          npm run build

      - name: Deploy with Google Cloud SDK
        if: ${{ github.event.release.tag_name }}
        env:
          NEW_VERSION: ${{ github.event.release.tag_name }}
        run: |
          gcloud app deploy --quiet --no-promote --version=$NEW_VERSION
