name: Publish

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run scripts
        shell: bash
        env:
          SECRET_CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
        run: |
          for f in ./etc/scripts/*.sh; do
            echo running $f
            bash $f
          done
      - name: NPM install
        run: npm ci
      - name: NPM build
        run: npm run build
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          local-dir: ./build/
          server-dir: /domains/mathiasbosman.be/public_html/