name: Publish

on:
  release:
    types: [ published ]

jobs:
  deploy:
    name: Deploy 🚀
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run scripts
        shell: bash
        env:
          SECRET_CONTACT_EMAIL: ${{ secrets.CONTACT_EMAIL }}
        run: |
          for f in ./etc/scripts/*.sh; do
            echo running $f
            bash $f
          done
      - name: NPM install
        run: npm ci
      - name: NPM build
        run: npm run build
      - name: GitHub Pages Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: gh-pages
          folder: build