name: Release
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test

  release:
    name: Patch 📦
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Patch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          npm run prepPatch
          git push