name: Testing
on: pull_request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run unit tests
        run: pnpm test:unit

  component-tests:
    timeout-minutes: 5
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run component tests
        run: pnpm test:component

  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Run build
        run: pnpm build

      - uses: actions/upload-artifact@v4
        name: Upload build folder
        with:
          name: pnpm-build
          path: ./dist/
          retention-days: 1

  e2e:
    needs: build
    timeout-minutes: 5
    strategy:
      matrix:
        browser: ['chrome', 'electron', 'edge']
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: pnpm-build
          path: ./dist/

      - name: E2E - ${{ matrix.browser }}
        uses: cypress-io/github-action@v6
        with:
          project: './test/driver/cypress'
          browser: ${{ matrix.browser }}
          start: pnpm preview:local
          wait-on: 'http://localhost:9000'
          wait-on-timeout: 30
          spec: '**/e2e/app/**/*'

      - uses: actions/upload-artifact@v4
        name: Upload screenshots
        with:
          name: e2e-${{ matrix.browser }}-screenshots
          path: ./test/driver/cypress/screenshots/
